### ISSUE TITLE
LED fading too advanced?!

### ISSUE THREAD

**Issue by idstudiolab** [id-studiolab/pomodoro#2]
Reading through the 07_led_animations, I am afraid that it is too complex for our purpose. Don't know how much this is tied into the instruction already and I do not want to jeopardise the progress for making the movies...

If still possible I would propose a simple (state machine based) code that just fades-up and down, with the possibility of change the fade color while fading.

Then leave the fancy stuff to the engaged or advanced student.

**Comment by idstudiolab** [comment]
My second issue!
The complexity is also due to the using the FastLED library - for only one LED!

**Comment by lorenzoromagnoli** [comment]
@idstudiolab, I love that you opened an issue! Next time please mention me in the issue or assign it to me so that I get notified. 

Let's do one issue at a time then.
1) I agree that the led crossfade function is quite complex. I'm not planning to do the code of that exercise live in the video, but I want to pack this, together with a series of other animations in a  demo sketch which I will briefly describe during the video class. Especially I will try to explain which bits and pieces of the sketch need to be copy pasted in case you want to experiment with this type of animations while programming your pomodoro timer.

**Comment by lorenzoromagnoli** [comment]
@idstudiolab have a look at [this](https://github.com/id-studiolab/pomodoro/blob/master/arduino_code/07a_led_animations_simple/07a_led_animations_simple.ino)
 
if we leave out the possibility of crossfading between two colours everything looks simpler.
